# Menus
menu:
  Home: /
  About: /kory-becker/
  Contact: /contact/
  Subscribe: http://feedburner.google.com/fb/a/mailverify?uri=PrimaryObjects
  Categories:

# Customize
customize:
  logo:
    url: /images/primaryobjects-w.png
    width: 248
    height: 33
    margin:
      top: 5
  theme_color: '#3b8dbd'
  highlight: tomorrow-night
  sidebar: left # sidebar position, options: left, right
  sidebar_gradient: 'linear-gradient(to right, #3b8dbd, rgb(216, 0, 255))'
  tags_position: bottom # top, bottom
  thumbnail: true # enable posts thumbnail, options: true, false
  showAuthor: true
  favicon: /favicon.ico # path to favicon
  social_links: # for more icons, please see http://fontawesome.io/icons/#brand
    twitter: https://twitter.com/primaryobjects
    google-plus: https://plus.google.com/107815270870071104283/posts
    github: https://github.com/primaryobjects
    linkedin: http://www.linkedin.com/in/korybecker
    rss: http://feeds.feedburner.com/PrimaryObjects

# Widgets
widgets:
  - recent_posts
  - category
  - links

# Search
search:
  insight: false # you need to install `hexo-generator-json-content` before using Insight Search
  swiftype: # enter swiftype install key here
  baidu: false # you need to disable other search engines to use Baidu search, options: true, false

# Comment
comment:
  disqus: primaryobjects # enter disqus shortname here
  duoshuo: # enter duoshuo shortname here
  youyan: # enter youyan uid here

# Share
share: default # options: jiathis, bdshare, addtoany, default

# Plugins
plugins:
  fancybox: true # options: true, false
  scrollLoading: true # options: true, false
  google_analytics: UA-843113-2 # enter the tracking ID for your Google Analytics
  baidu_analytics: # enter Baidu Analytics hash key

# Miscellaneous
miscellaneous:
  open_graph: # see http://ogp.me
    fb_app_id:
    fb_admins:
    twitter_id: PrimaryObjects
    google_plus: https://plus.google.com/107815270870071104283/posts
  links:
    Archive: /archives/